version: '3'
services:
  nginx-proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  container1:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
    depends_on:
      - nginx-proxy

  container2:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
    depends_on:
      - nginx-proxy

  container3:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
    depends_on:
      - nginx-proxy

  container4:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
    depends_on:
      - nginx-proxy
