version: '3'
services:
  container1:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
  container2:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
  container3:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
  container4:
    image: bomberman997/pdf-client-billserver
    restart: always
    expose:
      - 8080
  nginx-proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - container1
      - container2
      - container3
      - container4
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
